name = "TTNKit"
uuid = "b44c321c-291e-437f-af1d-05cac99632ef"
authors = ["Niklas Tausendpfund <n.tausendpfund@fz-juelich.de>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
